language: erlang
notifications:
  recipients:
    - alexis.tabary@gmail.com
otp_release:
  - 17.1
env:
  - ELIXIR_VERSION=1.0.2
before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
  - unzip -d elixir Precompiled.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: mix test
